#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ -f $OPENSHIFT_REPO_DIR/rebuild ]
then
  cd $OPENSHIFT_REPO_DIR/
  virtualenv .
  export PYTHON_EGG_CACHE=$OPENSHIFT_TMP_DIR/.python-eggs PYTHONPATH=$OPENSHIFT_REPO_DIR/lib/python2.6/site-packages
  ./bin/easy_install lxml
  ./bin/easy_install pil
  ./bin/easy_install psycopg2
  ./bin/python setup.py develop
fi
