#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR/

## apply database config
virtualenv .
export PYTHON_EGG_CACHE=$OPENSHIFT_TMP_DIR/.python-eggs PYTHONPATH=$OPENSHIFT_REPO_DIR/lib/python2.6/site-packages
./bin/gmg dbupdate
