#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR/

## apply database config
. $OPENSHIFT_REPO_DIR/setpath
virtualenv .
./bin/gmg dbupdate
