#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

cd $OPENSHIFT_REPO_DIR/
virtualenv .
export PYTHONPATH=$OPENSHIFT_REPO_DIR/lib/python2.6/site-packages PYTHON_EGG_CACHE=$OPENSHIFT_TMP_DIR/.python-eggs
./lazyserver.sh --server-name=openshift >> $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &

